change container registry to private ecr

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -6,7 +6,6 @@ on:
     branches:
       - exp
       - main
-      - feature/**
     tags: ["**"]
 
 permissions:
@@ -64,7 +63,7 @@ jobs:
         run: make _build
 
   build-and-push-image:
-    if: github.ref == 'refs/heads/exp' || startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/tags/')
+    if: github.ref == 'refs/heads/exp' || startsWith(github.ref, 'refs/tags/')
     runs-on: ubuntu-latest
     needs:
       - test
@@ -73,29 +72,28 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Get 10 length commit sha
-        if: github.ref == 'refs/heads/exp' || startsWith(github.ref, 'refs/heads/feature/')
-        id: short-sha
+      - name: Get image tag
+        id: image-tag
         run: |
-          echo value=$(echo ${{ github.sha }} | cut -c1-10) >> $GITHUB_OUTPUT
+          if [[ "${{ github.ref }}" == 'refs/heads/exp' ]] ; then
+            echo tag=$(echo ${{ github.sha }} | cut -c1-10) >> $GITHUB_OUTPUT
+          elif [[ "${{ github.ref }}" == 'refs/tags/' ]] ; then
+            echo tag=$(echo "$GITHUB_REF_NAME" ) >> $GITHUB_OUTPUT
+          else
+            echo "Image tag cannot be set"
+            exit 1
+          fi
 
-      - name: Log in to the Container registry
-        uses: docker/login-action@v3
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
         with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
+          role-session-name: ${{ github.event.repository.name }}-actions
+          aws-region: ap-northeast-2
 
-      - name: Docker meta
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          images: |
-            ghcr.io/${{ github.repository }}
-          tags: |
-            type=raw,priority=100,prefix=exp-,value=${{ steps.short-sha.outputs.value }},enable=${{ startsWith(github.ref, 'refs/heads/exp') }}
-            type=raw,priority=100,prefix=feature-,value=${{ steps.short-sha.outputs.value }},enable=${{ startsWith(github.ref, 'refs/heads/feature/') }}
-            type=ref,priority=600,event=tag,enable=${{ startsWith(github.ref, 'refs/tags/') }}
+      - name: ECR login
+        id: ecr-login
+        uses: aws-actions/amazon-ecr-login@v2
 
       - name: Get current time
         id: time
@@ -108,12 +106,12 @@ jobs:
         with:
           platforms: linux/arm64
 
-      - name: Build image and push to GitHub Container Registry
+      - name: Build image and push to ECR
         uses: docker/build-push-action@v6
         with:
           context: .
           push: true
-          tags: ${{ steps.meta.outputs.tags }}
+          tags: ${{ steps.ecr-login.outputs.registry }}/${{ github.event.repository.name }}:${{ steps.image-tag.outputs.tag }}
           platforms: linux/arm64
           build-args: |
             BUILD_VERSION=${{ github.ref_name }}
